version: '3.1'
services:

  my-db:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  my-api:
    build: .
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://my-db:27017/bookstore
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    command: >
      bash -c "
        mvn clean package;
        java -jar target/book-api-*.jar;
      "
    depends_on:
      - my-db